-- MySQL Script generated by MySQL Workbench
-- Τετ 16 Νοέ 2016 03:40:00 μμ EET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema easyDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `easyDB` ;

-- -----------------------------------------------------
-- Schema easyDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `easyDB` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `easyDB` ;

-- -----------------------------------------------------
-- Table `easyDB`.`Nodes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easyDB`.`Nodes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `easyDB`.`Nodes` (
  `Channel_0` VARCHAR(45) NOT NULL,
  `Channel_1` VARCHAR(45) NOT NULL,
  `Channel_2` VARCHAR(45) NOT NULL,
  `Channel_3` VARCHAR(45) NOT NULL,
  `Channel_4` VARCHAR(45) NOT NULL,
  `Channel_5` VARCHAR(45) NOT NULL,
  `Channel_6` VARCHAR(45) NOT NULL,
  `Channel_7` VARCHAR(45) NOT NULL,
  `Samplerate` VARCHAR(45) NOT NULL,
  `Location` VARCHAR(45) NOT NULL,
  `NetworkCode` VARCHAR(45) NOT NULL,
  `StationID` VARCHAR(45) NOT NULL,
  `LocationID` VARCHAR(45) NULL,
  `Latitude` VARCHAR(45) NOT NULL,
  `Longitude` VARCHAR(45) NOT NULL,
  `Magnitude` FLOAT NOT NULL,
  `Timestamp` VARCHAR(45) NOT NULL,
  `Triggered` TINYINT(1) NOT NULL,
  PRIMARY KEY (`StationID`))
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE UNIQUE INDEX `StationID_UNIQUE` ON `easyDB`.`Nodes` (`StationID` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `easyDB`.`Triggering`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `easyDB`.`Triggering` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `easyDB`.`Triggering` (
  `StationID` VARCHAR(45) NOT NULL,
  `maxrecaz` DOUBLE NOT NULL,
  `maxrecvz` DOUBLE NOT NULL,
  `maxrecdz` DOUBLE NOT NULL,
  `tauc` DOUBLE NOT NULL,
  `azi` DOUBLE NOT NULL,
  `mw` DOUBLE NOT NULL,
  `idx` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `timestamp` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idx`),
  CONSTRAINT `fk_station`
    FOREIGN KEY (`StationID`)
    REFERENCES `easyDB`.`Nodes` (`StationID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

SHOW WARNINGS;
CREATE INDEX `fk_Triggering_1_idx` ON `easyDB`.`Triggering` (`StationID` ASC);

SHOW WARNINGS;
SET SQL_MODE = '';
GRANT USAGE ON *.* TO easyadmin;
 DROP USER easyadmin;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
SHOW WARNINGS;
CREATE USER 'easyadmin' IDENTIFIED BY 'toor';

GRANT ALL ON `easyDB`.* TO 'easyadmin';
GRANT SELECT ON TABLE `easyDB`.* TO 'easyadmin';
GRANT SELECT, INSERT, TRIGGER ON TABLE `easyDB`.* TO 'easyadmin';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `easyDB`.* TO 'easyadmin';
SHOW WARNINGS;

-- -----------------------------------------------------
-- Data for table `easyDB`.`Nodes`
-- -----------------------------------------------------
START TRANSACTION;
USE `easyDB`;
INSERT INTO `easyDB`.`Nodes` (`Channel_0`, `Channel_1`, `Channel_2`, `Channel_3`, `Channel_4`, `Channel_5`, `Channel_6`, `Channel_7`, `Samplerate`, `Location`, `NetworkCode`, `StationID`, `LocationID`, `Latitude`, `Longitude`, `Magnitude`, `Timestamp`, `Triggered`) VALUES ('GNE', 'GNN', 'GNZ', 'MHE', 'MHN', 'MHZ', 'volt', 'temp', '100', 'U', 'XX', 'FAKE1', '00', '37.97897189', '23.6758315', 0, '-', 0);
INSERT INTO `easyDB`.`Nodes` (`Channel_0`, `Channel_1`, `Channel_2`, `Channel_3`, `Channel_4`, `Channel_5`, `Channel_6`, `Channel_7`, `Samplerate`, `Location`, `NetworkCode`, `StationID`, `LocationID`, `Latitude`, `Longitude`, `Magnitude`, `Timestamp`, `Triggered`) VALUES ('GNE', 'GNN', 'GNZ', 'MHE', 'MHN', 'MHZ', 'volt', 'temp', '100', 'R', 'XX', 'FAKE2', '00', '38.25000000', '24.00000000', 0, '-', 1);
INSERT INTO `easyDB`.`Nodes` (`Channel_0`, `Channel_1`, `Channel_2`, `Channel_3`, `Channel_4`, `Channel_5`, `Channel_6`, `Channel_7`, `Samplerate`, `Location`, `NetworkCode`, `StationID`, `LocationID`, `Latitude`, `Longitude`, `Magnitude`, `Timestamp`, `Triggered`) VALUES ('GNE', 'GNN', 'GNZ', 'MHE', 'MHN', 'MHZ', 'volt', 'temp', '100', 'U', 'XX', 'FAKE3', '00', '37.996', '23.694', 0, '-', 0);

COMMIT;


-- -----------------------------------------------------
-- Data for table `easyDB`.`Triggering`
-- -----------------------------------------------------
START TRANSACTION;
USE `easyDB`;
INSERT INTO `easyDB`.`Triggering` (`StationID`, `maxrecaz`, `maxrecvz`, `maxrecdz`, `tauc`, `azi`, `mw`, `idx`, `timestamp`) VALUES ('dummy', 0, 0, 0, 0, 0, 0, 0, '0');

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
